version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  migration:
    image: node:lts-alpine
    command: npm run migrate
    volumes:
      - ./:/app
    links:
      - mysql
    depends_on:
      - mysql
  web:
    build: .
    command: npm start
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - migration
volumes:
  database:
    driver: "local"